<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>ae6a7ccd-0c7a-4417-b657-051ab1b441e2</UserSecretsId>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <!-- Azure / legacy -->
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.4" />
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="3.0.4" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.14" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.3.0" />

    <!-- Entity Framework Core (aligned) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />

    <!-- ASP.NET / tooling -->
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="9.0.11" />

    <!-- Logging / config -->
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.11" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />

    <!-- OpenAPI / Swagger -->
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

    <!-- Misc -->
    <PackageReference Include="PagedList.Core.Mvc" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="images\" />
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\skyimages.json" CodeGenerator="NSwagCSharp" Namespace="imageWebservice">
      <SourceUri>https://imageIngest.azurewebsites.net/api/skyimages</SourceUri>
    </OpenApiReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="skyImages.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
